// Generated by Design OS Motion IR Compiler
// Target: GreenSock GSAP Timeline (Sequenced)

import gsap from "gsap";

export function createAnimation(containerSelector = ".motion-canvas") {
  const tl = gsap.timeline({
    repeat: -1,
  });

  // Track for #bell-body (Transform)
  gsap.set("#bell-body", { transformOrigin: "24px 8px" });
  tl.to("#bell-body", {
    keyframes: [
      { rotation: 0, duration: 0.13333333333333333 },
      { rotation: 14, duration: 0.13333333333333333 },
      { rotation: -12, duration: 0.13333333333333333 },
      { rotation: 8, duration: 0.13333333333333333 },
      { rotation: -3, duration: 0.13333333333333333 },
      { rotation: 0, duration: 0.13333333333333333 }
    ],
    ease: "power2.out",
    delay: 0
  }, 0);

  // Track for #bell-clapper (Transform)
  gsap.set("#bell-clapper", { transformOrigin: "24px 38px" });
  tl.to("#bell-clapper", {
    keyframes: [
      { x: 0, y: 0, duration: 0.15 },
      { x: -4, y: 0, duration: 0.15 },
      { x: 4, y: 0, duration: 0.15 },
      { x: -2, y: 0, duration: 0.15 },
      { x: 0, y: 0, duration: 0.15 }
    ],
    ease: "power2.out",
    delay: 0.05
  }, 0);

  return tl;
}