#!/usr/bin/env node
/**
 * restructure.mjs — one-off repository reorganisation (kept as the record of what moved).
 *
 *   1. git mv every file per the mapping in plan.md;
 *   2. rewrite every path token that resolves to a moved file (or, inside a moved file,
 *      to any file), resolving tokens against: the referencing file's folder, the repo
 *      root, promo/ (dev-server URLs), and docs/ (github.io URLs); `.html` tokens may name
 *      a Jekyll `.md` page;
 *   3. write redirect stubs at every old public Pages URL (docs/**) that moved.
 *
 * Usage: node plans/260926-repo-structure/restructure.mjs --dry-run | --apply
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const apply = process.argv.includes('--apply');
const SITE = 'https://jangtrinh.github.io/design-os-svg-animation/';
const NEVER_EDIT = new Set(['package.json', 'package-lock.json', 'knowledge/INDEX.md']); // another session's uncommitted work
const NEVER_EDIT_DIRS = ['plans/260926-repo-structure/', 'node_modules/'];
const TEXT = /\.(md|html|mjs|js|cjs|ts|tsx|py|json|ya?ml|css|txt|xml|sh)$/;

const tracked = String(execFileSync('git', ['ls-files'])).split('\n').filter(Boolean);
const oldFiles = new Set(tracked);

// ---- mapping (promo-relative rule applies to promo/ and its docs/promo mirror) ----
function promoRule(rel) {
  const [head] = rel.split('/');
  if (/^hyperframes-(engine|extra-beats|motion-presets)\.mjs$/.test(rel) || rel === 'studio-runner.css') return `shared/${rel}`;
  if (['index.html', 'promo-engine.js', 'promo.css', 'promo-storyboard.svg'].includes(rel)) return `design-os-promo/${rel}`;
  if (rel.startsWith('claude-design')) return `claude-design/${rel}`;
  if (rel.startsWith('codex-app')) return `codex-app/${rel}`;
  if (rel.startsWith('v0-generative-ui') || rel === 'guillermo.png') return `v0-generative-ui/${rel}`;
  if (rel.startsWith('design-os-tutorial') || head === 'assets') return `design-os-tutorial/${rel}`;
  if (rel.startsWith('astra-law')) return `astra-law/${rel}`;
  if (head === 'drone-404-proofs') return `drone-404/proofs/${rel.slice('drone-404-proofs/'.length)}`;
  if (rel === 'drone-404.html' || rel.startsWith('drone-search-404.')) return `drone-404/${rel}`;
  if (head === 'drone-404') return null; // old Pages module copies: regenerated by sync-line-art-pages
  if (/^sample-.*\.html$/.test(rel) || rel === 'hyperframes-demo.html') return `samples/${rel}`;
  return rel;
}

const DOCS_GROUPS = {
  architecture: ['architecture-overview.md', 'architecture-supplement.md', 'system-architecture.md', 'architecture-dashboard.html'],
  pipelines: ['motion-video-recreation-pipeline.md', 'motion-video-recreation-workflow-guide.md', 'line-art-to-motion-pipeline.md', 'multimodal-ingestion-pipeline.md'],
  reference: ['motion-ir.md', 'motion-ir-specification.md', 'morphing-topology-strategy.md', 'quality-and-safety-gates.md', 'setup-and-toolchain.md', 'ai-capabilities-and-limits.md', 'ai-capabilities-and-repair.md', 'knowledge-and-auto-research.md', 'gates-audit-proof.html', 'primitives-showcase.html'],
  'cases/codex-app': ['codex-app-recreation-contract.md', 'codex-app-screenplay-v2.md'],
  'cases/v0-generative-ui': ['v0-generative-ui-recreation-contract.md', 'v0-generative-ui.contact-sheet.jpg', 'v0-generative-ui.cuts.json'],
  'cases/saas-short': ['saas-short.contact-sheet.jpg'],
};

function newPath(file) {
  if (file.startsWith('promo/')) { const to = promoRule(file.slice(6)); return to && `promo/${to}`; }
  if (file.startsWith('docs/promo/')) { const to = promoRule(file.slice(11)); return to && `docs/promo/${to}`; }
  if (file.startsWith('docs/') && !file.slice(5).includes('/')) {
    for (const [dir, names] of Object.entries(DOCS_GROUPS)) if (names.includes(file.slice(5))) return `docs/${dir}/${file.slice(5)}`;
  }
  if (/^research\/2026-09-codex-.*\.md$/.test(file)) return `research/codex-app/${path.basename(file)}`;
  if (file === 'research/multi-persona-debate-log.md') return 'research/notes/multi-persona-debate-log.md';
  if (['plans/astra-for-law-recreation.md', 'plans/astra-law-temporal-audit.md', 'plans/drone-404-svg-animation.md'].includes(file)) return `plans/cases/${path.basename(file)}`;
  return file;
}

const moves = new Map(); // old -> new (null = delete)
for (const f of tracked) { const to = newPath(f); if (to !== f) moves.set(f, to); }
const dirMoves = new Map([
  ['promo/astra-law-icons', 'promo/astra-law/astra-law-icons'], ['docs/promo/astra-law-icons', 'docs/promo/astra-law/astra-law-icons'],
  ['promo/assets', 'promo/design-os-tutorial/assets'], ['promo/drone-404-proofs', 'promo/drone-404/proofs'],
]);
const whereNow = old => (moves.has(old) ? moves.get(old) : old);
const oldDirs = new Set(tracked.flatMap(f => f.split('/').slice(0, -1).map((_, i, a) => a.slice(0, i + 1).join('/'))));

// ---- token rewriting ----
const TOKEN = /(?:https:\/\/jangtrinh\.github\.io\/design-os-svg-animation\/)?[A-Za-z0-9_@.~\-/]*[A-Za-z0-9_-](?:\.(?:html|mjs|js|css|json|png|jpg|jpeg|svg|mp4|gif|md|txt|py)\b|(?=['"`/)\s]))/g;

function resolveTarget(candidate) {
  const p = path.posix.normalize(candidate);
  if (oldFiles.has(p)) return { old: p };
  if (dirMoves.has(p) || oldDirs.has(p)) return { old: p, dir: true };
  if (p.endsWith('.html') && oldFiles.has(p.replace(/\.html$/, '.md'))) return { old: p.replace(/\.html$/, '.md'), page: true };
  return null;
}
const newLocation = ({ old, dir, page }) => {
  const now = dir ? (dirMoves.get(old) ?? old) : whereNow(old);
  return now && (page ? now.replace(/\.md$/, '.html') : now);
};

function rewriteToken(token, oldFile, newFile) {
  const fileMoved = oldFile !== newFile;
  if (token.startsWith(SITE)) {
    const hit = resolveTarget(path.posix.join('docs', token.slice(SITE.length)));
    const to = hit && newLocation(hit);
    return to && to.startsWith('docs/') ? SITE + to.slice(5) : token;
  }
  const rooted = token.startsWith('/');
  const bare = rooted ? token.slice(1) : token;
  const bases = rooted ? [['', 'root'], ['promo', 'promo']] : [[path.posix.dirname(oldFile), 'self'], ['', 'root'], ['promo', 'promo']];
  for (const [base, kind] of bases) {
    const hit = resolveTarget(path.posix.join(base, bare));
    if (!hit) continue;
    const moved = hit.dir ? dirMoves.has(hit.old) : moves.has(hit.old);
    if (!moved && !(fileMoved && kind === 'self')) return token; // nothing changed for this reference
    const to = newLocation(hit);
    if (!to) return token;
    let out;
    if (kind === 'self') {
      out = path.posix.relative(path.posix.dirname(newFile), to) || path.posix.basename(to);
      if (token.startsWith('./') && !out.startsWith('.')) out = `./${out}`;
    } else if (kind === 'root') out = to;
    else out = path.posix.relative('promo', to);
    return rooted ? `/${out}` : out;
  }
  return token;
}

const edits = [];
for (const oldFile of tracked) {
  const newFile = whereNow(oldFile);
  if (!newFile || !TEXT.test(oldFile) || NEVER_EDIT.has(oldFile) || NEVER_EDIT_DIRS.some(d => oldFile.startsWith(d))) continue;
  const text = fs.readFileSync(oldFile, 'utf8');
  let changed = 0;
  const next = text.replace(TOKEN, token => { const out = rewriteToken(token, oldFile, newFile); if (out !== token) changed += 1; return out; });
  if (changed) edits.push({ oldFile, newFile, changed, next });
}

// Files we must not edit but that reference moved paths: report them.
const blocked = [...NEVER_EDIT].filter(f => oldFiles.has(f) && fs.existsSync(f)).filter(f => {
  const text = fs.readFileSync(f, 'utf8');
  return [...text.matchAll(TOKEN)].some(([t]) => rewriteToken(t, f, f) !== t);
});

// ---- redirect stubs for old public URLs ----
const stubs = [];
for (const [from, to] of moves) {
  if (!to || !from.startsWith('docs/') || from.startsWith('docs/promo/drone-404/')) continue;
  if (!/\.(html|md)$/.test(from)) continue;
  const oldUrl = from.replace(/\.md$/, '.html');
  const target = path.posix.relative(path.posix.dirname(oldUrl), to.replace(/\.md$/, '.html'));
  stubs.push([oldUrl, target]);
}
const stubHtml = target => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Moved</title>
<meta name="robots" content="noindex">
<link rel="canonical" href="${target}">
<meta http-equiv="refresh" content="0; url=${target}">
</head>
<body><p>This page moved to <a href="${target}">${target}</a>.</p></body>
</html>
`;

console.log(`moves: ${moves.size} files (${[...moves.values()].filter(v => v === null).length} deleted) · rewritten files: ${edits.length} (${edits.reduce((n, e) => n + e.changed, 0)} tokens) · redirect stubs: ${stubs.length}`);
if (blocked.length) console.log(`NOT EDITED (other session's uncommitted work) but referencing moved paths: ${blocked.join(', ')}`);
const show = process.argv.includes('--show') ? process.argv.slice(process.argv.indexOf('--show') + 1) : [];
for (const e of edits.filter(x => show.includes(x.oldFile))) {
  const tmp = `/tmp/restructure-preview-${path.basename(e.oldFile)}`;
  fs.writeFileSync(tmp, e.next);
  try { execFileSync('diff', ['-u', e.oldFile, tmp], { stdio: 'pipe' }); } catch (d) { console.log(String(d.stdout)); }
  fs.rmSync(tmp);
}
if (!apply) {
  if (show.length) process.exit(0);
  for (const e of edits) console.log(`  ${e.oldFile}${e.newFile !== e.oldFile ? ` -> ${e.newFile}` : ''}: ${e.changed}`);
  for (const [u, t] of stubs) console.log(`  stub ${u} -> ${t}`);
  process.exit(0);
}

for (const [from, to] of moves) {
  if (to === null) { execFileSync('git', ['rm', '-q', from]); continue; }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  execFileSync('git', ['mv', from, to]);
}
for (const e of edits) fs.writeFileSync(e.newFile, e.next);
for (const [url, target] of stubs) { fs.mkdirSync(path.dirname(url), { recursive: true }); fs.writeFileSync(url, stubHtml(target)); }
execFileSync('git', ['add', '-A', 'promo', 'docs', 'research', 'plans', 'scripts', 'src', 'tests', 'README.md', 'AGENTS.md', 'CLAUDE.md', 'CONTEXT.md', 'skills', '.github', 'examples', 'playground', 'fixtures', 'schemas']);
console.log('applied');
