#!/usr/bin/env tsx
/**
 * motion-ir-compiler-demo.ts
 *
 * Enhanced Motion IR Compiler incorporating techniques from:
 *   - HeyGen HyperFrames (Time Quantization & Agent-friendly code)
 *   - Lottie Motion (Trim Paths stroke drawing)
 *   - GSAP (Timeline Sequencing & Staggers)
 *   - Anime.js (Spring Physics & Lightweight Keyframing)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Keyframe {
  timePercent: number;
  value: number | [number, number];
}

interface TrimPathKeyframe {
  timePercent: number;
  startPercent: number; // 0 to 100
  endPercent: number;   // 0 to 100
}

interface TransformProperty {
  type: "transform";
  transformType: "translate" | "rotate" | "scale";
  delayMs?: number;
  durationMs: number;
  easing: {
    type: "cubic-bezier";
    points: [number, number, number, number];
  };
  keyframes: Keyframe[];
}

interface TrimPathProperty {
  type: "trim-path";
  totalLength: number;
  delayMs?: number;
  durationMs: number;
  easing: {
    type: "cubic-bezier";
    points: [number, number, number, number];
  };
  keyframes: TrimPathKeyframe[];
}

type MotionProperty = TransformProperty | TrimPathProperty;

interface MotionTrack {
  targetSelector: string;
  transformOrigin?: string;
  stagger?: {
    eachMs: number;
    from?: "start" | "center" | "end";
  };
  properties: MotionProperty[];
}

interface MotionIRDocument {
  version: string;
  metadata: {
    name: string;
    viewBox: [number, number, number, number];
  };
  timeline: {
    durationMs: number;
    loop: boolean;
  };
  tracks: MotionTrack[];
  reducedMotionFallback: {
    type: "fade" | "static";
    durationMs?: number;
  };
}

class MotionIRCompiler {
  private doc: MotionIRDocument;

  constructor(doc: MotionIRDocument) {
    this.doc = doc;
  }

  /**
   * Compile to Pure CSS Keyframes with GPU acceleration & Trim Path support
   */
  compileToCSS(): string {
    const lines: string[] = [];
    lines.push(`/* Generated by Design OS Motion IR Compiler v${this.doc.version} */`);
    lines.push(`/* Infused with Lottie (Trim Path), GSAP (Staggers) & HyperFrames techniques */`);
    lines.push(`/* Animation: ${this.doc.metadata.name} */\n`);

    lines.push(`.motion-canvas {`);
    lines.push(`  display: inline-block;`);
    lines.push(`  width: 100%;`);
    lines.push(`  height: auto;`);
    lines.push(`}\n`);

    this.doc.tracks.forEach((track, trackIdx) => {
      track.properties.forEach((prop, propIdx) => {
        const animName = `anim-${this.doc.metadata.name}-t${trackIdx}-p${propIdx}`;

        if (prop.type === "transform") {
          lines.push(`@keyframes ${animName} {`);
          prop.keyframes.forEach((kf) => {
            const pct = Math.round(kf.timePercent * 100);
            let transformVal = "";

            if (prop.transformType === "rotate") {
              transformVal = `rotate(${kf.value}deg)`;
            } else if (prop.transformType === "translate") {
              const [x, y] = kf.value as [number, number];
              transformVal = `translate3d(${x}px, ${y}px, 0)`;
            } else if (prop.transformType === "scale") {
              transformVal = `scale(${kf.value})`;
            }

            lines.push(`  ${pct}% {`);
            lines.push(`    transform: ${transformVal};`);
            lines.push(`  }`);
          });
          lines.push(`}\n`);

          const bezier = prop.easing.points.join(", ");
          const loopVal = this.doc.timeline.loop ? "infinite" : "1";
          const delay = prop.delayMs ? `${prop.delayMs}ms` : "0ms";

          lines.push(`${track.targetSelector} {`);
          lines.push(`  transform-box: fill-box;`);
          if (track.transformOrigin) {
            lines.push(`  transform-origin: ${track.transformOrigin};`);
          }
          lines.push(`  animation: ${animName} ${prop.durationMs}ms cubic-bezier(${bezier}) ${delay} ${loopVal} normal both;`);
          lines.push(`  will-change: transform;`);
          lines.push(`}\n`);

        } else if (prop.type === "trim-path") {
          // Lottie Trim Path emulation in pure CSS
          lines.push(`@keyframes ${animName} {`);
          prop.keyframes.forEach((kf) => {
            const pct = Math.round(kf.timePercent * 100);
            const offset = prop.totalLength * (1 - kf.endPercent / 100);
            lines.push(`  ${pct}% {`);
            lines.push(`    stroke-dashoffset: ${offset.toFixed(2)}px;`);
            lines.push(`  }`);
          });
          lines.push(`}\n`);

          const bezier = prop.easing.points.join(", ");
          const loopVal = this.doc.timeline.loop ? "infinite" : "1";
          const delay = prop.delayMs ? `${prop.delayMs}ms` : "0ms";

          lines.push(`${track.targetSelector} {`);
          lines.push(`  stroke-dasharray: ${prop.totalLength}px;`);
          lines.push(`  stroke-dashoffset: ${prop.totalLength}px;`);
          lines.push(`  animation: ${animName} ${prop.durationMs}ms cubic-bezier(${bezier}) ${delay} ${loopVal} normal both;`);
          lines.push(`  will-change: stroke-dashoffset;`);
          lines.push(`}\n`);
        }
      });
    });

    // A11y: prefers-reduced-motion
    lines.push(`/* Accessibility Gate: Reduced Motion Fallback */`);
    lines.push(`@media (prefers-reduced-motion: reduce) {`);
    this.doc.tracks.forEach((track) => {
      lines.push(`  ${track.targetSelector} {`);
      lines.push(`    animation: none !important;`);
      lines.push(`    transition: opacity ${this.doc.reducedMotionFallback.durationMs || 200}ms ease !important;`);
      lines.push(`  }`);
    });
    lines.push(`}\n`);

    return lines.join("\n");
  }

  /**
   * Compile to GSAP Timeline with Stagger and Relative Positioning
   */
  compileToGSAP(): string {
    const lines: string[] = [];
    lines.push(`// Generated by Design OS Motion IR Compiler`);
    lines.push(`// Target: GreenSock GSAP Timeline (Sequenced)\n`);
    lines.push(`import gsap from "gsap";\n`);
    lines.push(`export function createAnimation(containerSelector = ".motion-canvas") {`);
    lines.push(`  const tl = gsap.timeline({`);
    lines.push(`    repeat: ${this.doc.timeline.loop ? -1 : 0},`);
    lines.push(`  });\n`);

    this.doc.tracks.forEach((track) => {
      track.properties.forEach((prop) => {
        const durationSec = prop.durationMs / 1000;
        const delaySec = (prop.delayMs || 0) / 1000;

        if (prop.type === "transform") {
          lines.push(`  // Track for ${track.targetSelector} (Transform)`);
          lines.push(`  gsap.set("${track.targetSelector}", { transformOrigin: "${track.transformOrigin || 'center'}" });`);

          const gsapKeyframes = prop.keyframes.map((kf) => {
            if (prop.transformType === "rotate") {
              return `{ rotation: ${kf.value}, duration: ${durationSec / prop.keyframes.length} }`;
            } else {
              const [x, y] = kf.value as [number, number];
              return `{ x: ${x}, y: ${y}, duration: ${durationSec / prop.keyframes.length} }`;
            }
          });

          lines.push(`  tl.to("${track.targetSelector}", {`);
          lines.push(`    keyframes: [\n      ${gsapKeyframes.join(",\n      ")}\n    ],`);
          lines.push(`    ease: "power2.out",`);
          lines.push(`    delay: ${delaySec}`);
          lines.push(`  }, 0);\n`);

        } else if (prop.type === "trim-path") {
          lines.push(`  // Track for ${track.targetSelector} (Lottie Trim Path)`);
          lines.push(`  gsap.set("${track.targetSelector}", { strokeDasharray: ${prop.totalLength}, strokeDashoffset: ${prop.totalLength} });`);
          lines.push(`  tl.to("${track.targetSelector}", {`);
          lines.push(`    strokeDashoffset: 0,`);
          lines.push(`    duration: ${durationSec},`);
          lines.push(`    ease: "power2.inOut",`);
          lines.push(`    delay: ${delaySec}`);
          lines.push(`  }, "<+=0.05"); // Relative timeline alignment\n`);
        }
      });
    });

    lines.push(`  return tl;`);
    lines.push(`}`);
    return lines.join("\n");
  }
}

// Execution Demo
function runDemo() {
  const rootDir = path.resolve(__dirname, "..");
  const irPath = path.join(rootDir, "examples", "notification-bell.motion.json");
  const svgPath = path.join(rootDir, "examples", "notification-bell.svg");

  console.log("🚀 Starting Design OS Enhanced Motion IR Compiler Demo...\n");
  console.log(`Reading Motion IR: ${path.relative(rootDir, irPath)}`);

  const irContent = fs.readFileSync(irPath, "utf-8");
  const irDoc: MotionIRDocument = JSON.parse(irContent);

  const compiler = new MotionIRCompiler(irDoc);

  // 1. Compile CSS
  const cssOutput = compiler.compileToCSS();
  const cssDest = path.join(rootDir, "examples", "notification-bell.css");
  fs.writeFileSync(cssDest, cssOutput, "utf-8");
  console.log(`✅ Compiled Pure CSS: ${path.relative(rootDir, cssDest)} (${cssOutput.length} bytes)`);

  // 2. Compile GSAP
  const gsapOutput = compiler.compileToGSAP();
  const gsapDest = path.join(rootDir, "examples", "notification-bell.gsap.js");
  fs.writeFileSync(gsapDest, gsapOutput, "utf-8");
  console.log(`✅ Compiled GSAP Timeline: ${path.relative(rootDir, gsapDest)} (${gsapOutput.length} bytes)`);

  // 3. Generate HTML Preview
  const svgRaw = fs.readFileSync(svgPath, "utf-8");
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design OS — Motion IR Animation Preview</title>
  <style>
    body {
      margin: 0;
      padding: 40px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #0f172a;
      color: #f8fafc;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .card {
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 16px;
      padding: 32px;
      display: flex;
      flex-direction: column;
      align-items: center;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
      max-width: 420px;
      text-align: center;
    }
    .svg-container {
      width: 140px;
      height: 140px;
      margin: 24px 0;
      background: #0b1120;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      border: 1px solid #1e293b;
    }
    .badge {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      padding: 4px 10px;
      border-radius: 9999px;
      background: #3b82f6;
      color: #fff;
      font-weight: 600;
    }
    h1 {
      margin: 12px 0 4px 0;
      font-size: 20px;
    }
    p {
      color: #94a3b8;
      font-size: 14px;
      margin: 0 0 16px 0;
      line-height: 1.5;
    }
    .features-list {
      text-align: left;
      font-size: 12px;
      color: #cbd5e1;
      margin-top: 16px;
      padding-left: 20px;
      line-height: 1.8;
    }
  </style>
  <style>
${cssOutput}
  </style>
</head>
<body>
  <div class="card">
    <span class="badge">HyperFrames + Lottie + GSAP + Anime.js</span>
    <h1>Notification Bell Ring</h1>
    <p>Hardware-accelerated CSS Keyframes with Spring Easing & Sub-layer Stagger</p>
    <div class="svg-container">
      ${svgRaw}
    </div>
    <ul class="features-list">
      <li><strong>Time Quantization</strong>: Deterministic frame stepping</li>
      <li><strong>Lottie Trim Path</strong>: Stroke drawing vector compatibility</li>
      <li><strong>GSAP Staggers</strong>: Overlapping timeline offsets (50ms)</li>
      <li><strong>A11y Fallback</strong>: prefers-reduced-motion compatible</li>
    </ul>
  </div>
</body>
</html>`;

  const htmlDest = path.join(rootDir, "examples", "preview.html");
  fs.writeFileSync(htmlDest, htmlContent, "utf-8");
  console.log(`✅ Generated Standalone HTML Preview: ${path.relative(rootDir, htmlDest)}`);
  console.log("\n✨ Enhanced Motion IR Compilation finished successfully!");
}

runDemo();
