#!/usr/bin/env tsx
/**
 * motion-ir-compiler-demo.ts
 *
 * Prototype compiler for Motion IR (Intermediate Representation).
 * Compiles a declarative Motion IR document into:
 *   1. Pure CSS Keyframes (Zero dependency, GPU accelerated)
 *   2. GSAP Timeline code snippet
 *   3. Standalone HTML interactive preview
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Keyframe {
  timePercent: number;
  value: number | [number, number];
}

interface TransformProperty {
  type: "transform";
  transformType: "translate" | "rotate" | "scale";
  delayMs?: number;
  durationMs: number;
  easing: {
    type: "cubic-bezier";
    points: [number, number, number, number];
  };
  keyframes: Keyframe[];
}

interface MotionTrack {
  targetSelector: string;
  transformOrigin?: string;
  properties: TransformProperty[];
}

interface MotionIRDocument {
  version: string;
  metadata: {
    name: string;
    viewBox: [number, number, number, number];
  };
  timeline: {
    durationMs: number;
    loop: boolean;
  };
  tracks: MotionTrack[];
  reducedMotionFallback: {
    type: "fade" | "static";
    durationMs?: number;
  };
}

class MotionIRCompiler {
  private doc: MotionIRDocument;

  constructor(doc: MotionIRDocument) {
    this.doc = doc;
  }

  /**
   * Compile to Pure CSS Keyframes with hardware acceleration and A11y
   */
  compileToCSS(): string {
    const lines: string[] = [];
    lines.push(`/* Generated by Design OS Motion IR Compiler v${this.doc.version} */`);
    lines.push(`/* Animation: ${this.doc.metadata.name} */\n`);

    // Root SVG container styling
    lines.push(`.motion-canvas {`);
    lines.push(`  display: inline-block;`);
    lines.push(`  width: 100%;`);
    lines.push(`  height: auto;`);
    lines.push(`}\n`);

    this.doc.tracks.forEach((track, trackIdx) => {
      track.properties.forEach((prop, propIdx) => {
        const animName = `anim-${this.doc.metadata.name}-t${trackIdx}-p${propIdx}`;

        // 1. Generate @keyframes
        lines.push(`@keyframes ${animName} {`);
        prop.keyframes.forEach((kf) => {
          const pct = Math.round(kf.timePercent * 100);
          let transformVal = "";

          if (prop.transformType === "rotate") {
            transformVal = `rotate(${kf.value}deg)`;
          } else if (prop.transformType === "translate") {
            const [x, y] = kf.value as [number, number];
            transformVal = `translate3d(${x}px, ${y}px, 0)`;
          } else if (prop.transformType === "scale") {
            transformVal = `scale(${kf.value})`;
          }

          lines.push(`  ${pct}% {`);
          lines.push(`    transform: ${transformVal};`);
          lines.push(`  }`);
        });
        lines.push(`}\n`);

        // 2. Generate element rule
        const bezier = prop.easing.points.join(", ");
        const loopVal = this.doc.timeline.loop ? "infinite" : "1";
        const delay = prop.delayMs ? `${prop.delayMs}ms` : "0ms";

        lines.push(`${track.targetSelector} {`);
        lines.push(`  transform-box: fill-box;`);
        if (track.transformOrigin) {
          lines.push(`  transform-origin: ${track.transformOrigin};`);
        }
        lines.push(`  animation: ${animName} ${prop.durationMs}ms cubic-bezier(${bezier}) ${delay} ${loopVal} normal both;`);
        lines.push(`  will-change: transform;`);
        lines.push(`}\n`);
      });
    });

    // 3. A11y: prefers-reduced-motion
    lines.push(`/* Accessibility Gate: Reduced Motion Fallback */`);
    lines.push(`@media (prefers-reduced-motion: reduce) {`);
    this.doc.tracks.forEach((track) => {
      lines.push(`  ${track.targetSelector} {`);
      lines.push(`    animation: none !important;`);
      lines.push(`    transition: opacity ${this.doc.reducedMotionFallback.durationMs || 200}ms ease !important;`);
      lines.push(`  }`);
    });
    lines.push(`}\n`);

    return lines.join("\n");
  }

  /**
   * Compile to GSAP Timeline snippet
   */
  compileToGSAP(): string {
    const lines: string[] = [];
    lines.push(`// Generated by Design OS Motion IR Compiler`);
    lines.push(`// Target: GreenSock GSAP Timeline\n`);
    lines.push(`import gsap from "gsap";\n`);
    lines.push(`export function createAnimation(containerSelector = ".motion-canvas") {`);
    lines.push(`  const tl = gsap.timeline({`);
    lines.push(`    repeat: ${this.doc.timeline.loop ? -1 : 0},`);
    lines.push(`  });\n`);

    this.doc.tracks.forEach((track) => {
      track.properties.forEach((prop) => {
        const durationSec = prop.durationMs / 1000;
        const delaySec = (prop.delayMs || 0) / 1000;
        lines.push(`  // Track for ${track.targetSelector}`);
        lines.push(`  gsap.set("${track.targetSelector}", { transformOrigin: "${track.transformOrigin || 'center'}" });`);

        // Generate keyframes tween
        const gsapKeyframes = prop.keyframes.map((kf) => {
          if (prop.transformType === "rotate") {
            return `{ rotation: ${kf.value}, duration: ${durationSec / prop.keyframes.length} }`;
          } else {
            const [x, y] = kf.value as [number, number];
            return `{ x: ${x}, y: ${y}, duration: ${durationSec / prop.keyframes.length} }`;
          }
        });

        lines.push(`  tl.to("${track.targetSelector}", {`);
        lines.push(`    keyframes: [\n      ${gsapKeyframes.join(",\n      ")}\n    ],`);
        lines.push(`    ease: "power2.out",`);
        lines.push(`    delay: ${delaySec}`);
        lines.push(`  }, 0);\n`);
      });
    });

    lines.push(`  return tl;`);
    lines.push(`}`);
    return lines.join("\n");
  }
}

// Execution Demo
function runDemo() {
  const rootDir = path.resolve(__dirname, "..");
  const irPath = path.join(rootDir, "examples", "notification-bell.motion.json");
  const svgPath = path.join(rootDir, "examples", "notification-bell.svg");

  console.log("🚀 Starting Design OS Motion IR Compiler Demo...\n");
  console.log(`Reading Motion IR: ${path.relative(rootDir, irPath)}`);

  const irContent = fs.readFileSync(irPath, "utf-8");
  const irDoc: MotionIRDocument = JSON.parse(irContent);

  const compiler = new MotionIRCompiler(irDoc);

  // 1. Compile CSS
  const cssOutput = compiler.compileToCSS();
  const cssDest = path.join(rootDir, "examples", "notification-bell.css");
  fs.writeFileSync(cssDest, cssOutput, "utf-8");
  console.log(`✅ Compiled Pure CSS: ${path.relative(rootDir, cssDest)} (${cssOutput.length} bytes)`);

  // 2. Compile GSAP
  const gsapOutput = compiler.compileToGSAP();
  const gsapDest = path.join(rootDir, "examples", "notification-bell.gsap.js");
  fs.writeFileSync(gsapDest, gsapOutput, "utf-8");
  console.log(`✅ Compiled GSAP Timeline: ${path.relative(rootDir, gsapDest)} (${gsapOutput.length} bytes)`);

  // 3. Generate HTML Preview
  const svgRaw = fs.readFileSync(svgPath, "utf-8");
  const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design OS — Motion IR Animation Preview</title>
  <style>
    body {
      margin: 0;
      padding: 40px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: #0f172a;
      color: #f8fafc;
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    .card {
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 16px;
      padding: 32px;
      display: flex;
      flex-direction: column;
      align-items: center;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.5);
    }
    .svg-container {
      width: 120px;
      height: 120px;
      margin: 24px 0;
    }
    .badge {
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      padding: 4px 10px;
      border-radius: 9999px;
      background: #3b82f6;
      color: #fff;
      font-weight: 600;
    }
    h1 {
      margin: 12px 0 4px 0;
      font-size: 20px;
    }
    p {
      color: #94a3b8;
      font-size: 14px;
      margin: 0 0 16px 0;
    }
  </style>
  <style>
${cssOutput}
  </style>
</head>
<body>
  <div class="card">
    <span class="badge">Motion IR Compiled</span>
    <h1>Notification Bell Ring</h1>
    <p>Hardware-accelerated CSS Keyframes with Spring Easing</p>
    <div class="svg-container">
      ${svgRaw}
    </div>
  </div>
</body>
</html>`;

  const htmlDest = path.join(rootDir, "examples", "preview.html");
  fs.writeFileSync(htmlDest, htmlContent, "utf-8");
  console.log(`✅ Generated Standalone HTML Preview: ${path.relative(rootDir, htmlDest)}`);
  console.log("\n✨ Motion IR Compilation finished successfully!");
}

runDemo();
